image: jhipster/jhipster:v6.7.1

cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - .gradle/
stages:
    - check
    - build
    - test
    - analyze
    - package
    - release
    - deploy

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
nohttp:
    stage: check
    script:
        - ./gradlew checkstyleNohttp --no-daemon

gradle-compile:
    stage: build
    script:
        - ./gradlew compileJava -x check -PnodeInstall --no-daemon
    artifacts:
        paths:
          - build/classes/
          - build/generated/
        expire_in: 1 day

gradle-test:
    stage: test
    script:
        - ./gradlew test -PnodeInstall --no-daemon
    artifacts:
        reports:
            junit: build/test-results/test/TEST-*.xml
        paths:
            - build/test-results/
            - build/jacoco/
        expire_in: 1 day

# gradle-integration-test:
#     stage: test
#     script:
#         - ./gradlew integrationTest -PnodeInstall --no-daemon
#     artifacts:
#         reports:
#             junit: build/test-results/integrationTest/TEST-*.xml
#         paths:
#             - build/test-results/
#             - build/jacoco/
#         expire_in: 1 day

sonar-analyze:
    stage: analyze
    except:
        - merge_requests
    dependencies:
        - gradle-test
        - gradle-integration-test
    script:
        - ./gradlew sonarqube --no-daemon -Dsonar.organization=aglomer -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=d7473bd09d22bc626a9c67fab78c326426e21753
    allow_failure: true

gradle-package:
    stage: package
    script:
        - ./gradlew bootJar -Pprod -x check --no-daemon
    artifacts:
        paths:
            - build/libs/*.jar
            - build/classes
        expire_in: 1 day

docker-push:
    stage: release
    variables:
        REGISTRY_URL: registry.gitlab.com
        IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
    dependencies:
        - gradle-package
    script:
        - ./gradlew jib -Pprod -Djib.to.image=$IMAGE_TAG -Djib.to.auth.username="gitlab-ci-token" -Djib.to.auth.password=$CI_BUILD_TOKEN
