version: '2'
services:
  uas-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/uas/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=uas
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
